# Generated by Django 5.0 on 2023-12-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_customer_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('u22', 'U22'), ('vip', 'VIP'), ('normal', 'Normal')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
