# Generated by Django 5.0 on 2023-12-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_schedulestaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='cinemaapi/cinemaa/static/popcorn.png', null=True, upload_to='images/'),
        ),
    ]
