# Generated by Django 5.0 on 2023-12-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulestaff',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/cinemaa/static/popcorn.png', null=True, upload_to='images/'),
        ),
    ]
