# Generated by Django 5.0 on 2023-12-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(max_length=225, primary_key=True, serialize=False, unique=True),
        ),
    ]
