# Generated by Django 5.0 on 2023-12-24 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_schedulegroup_ticketstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(choices=[('standard', 'standard'), ('premium', 'premium'), ('VIP', 'VIP')], default='standard', max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.DeleteModel(
            name='ScheduleGroup',
        ),
    ]
