# Generated by Django 5.0 on 2024-01-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_customer_delete_schedulegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.CharField(choices=[('standard', 'standard'), ('premium', 'premium'), ('VIP', 'VIP')], default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
