# Generated by Django 5.0 on 2023-12-25 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0011_customer_delete_schedulegroup'),
        ('cinemaa', '0006_seattype_showtime_type_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_type', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('booking_status', models.CharField(choices=[('successful', 'successful'), ('on-going', 'on-going')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.ticketstaff')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cinemaa.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cinemaa.showtime')),
            ],
        ),
    ]
