# Generated by Django 5.0 on 2024-01-05 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_customer_delete_schedulegroup'),
        ('booking', '0004_alter_booking_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='staff',
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
