# Generated by Django 5.0 on 2024-01-05 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_customer_delete_schedulegroup'),
        ('booking', '0005_remove_booking_staff_alter_booking_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.ticketstaff'),
        ),
    ]
