# Generated by Django 5.0 on 2024-01-05 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 17, 30, 6, 38490, tzinfo=datetime.timezone.utc)),
        ),
    ]
