# Generated by Django 5.0 on 2024-01-06 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 19, 30, 24, 851000, tzinfo=datetime.timezone.utc)),
        ),
    ]
