# Generated by Django 5.0 on 2024-01-08 07:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_booking_created_at_bookingdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 8, 7, 54, 44, 730249, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bookingdiscount',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='bookingdiscount',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.discount'),
        ),
    ]
