# Generated by Django 5.0 on 2024-01-08 08:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_booking_created_at'),
        ('cinemaa', '0014_alter_showtimeseat_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 8, 8, 10, 47, 434567, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaa.showtime'),
        ),
    ]
