# Generated by Django 5.0 on 2024-01-08 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_alter_booking_created_at_alter_discount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 8, 8, 20, 22, 658317, tzinfo=datetime.timezone.utc)),
        ),
    ]
