# Generated by Django 5.0 on 2024-01-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_alter_booking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('successful', 'successful'), ('on-going', 'on-going'), ('check-in', 'check-in')], default='on-going', max_length=50),
        ),
    ]
