# Generated by Django 5.0 on 2023-12-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
