# Generated by Django 5.0 on 2023-12-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaa', '0002_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, upload_to='video/'),
        ),
    ]
