# Generated by Django 5.0 on 2023-12-22 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaa', '0002_hall_type'),
        ('movie', '0005_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
        ),
    ]
