# Generated by Django 5.0 on 2024-01-05 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaa', '0007_remove_seat_hall_seat_showtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='showtime',
        ),
        migrations.AddField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cinemaa.hall'),
        ),
    ]
