# Generated by Django 5.0 on 2024-01-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaa', '0008_remove_seat_showtime_seat_hall'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together={('hall', 'id')},
        ),
    ]
