# Generated by Django 5.0 on 2024-01-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaa', '0010_alter_showtime_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together=set(),
        ),
    ]
