# Generated by Django 5.0 on 2024-01-06 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaa', '0011_alter_showtime_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='status',
        ),
        migrations.CreateModel(
            name='ShowtimeSeat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=50)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cinemaa.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cinemaa.showtime')),
            ],
        ),
    ]
