# Generated by Django 5.0 on 2024-01-08 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaa', '0012_remove_seat_status_showtimeseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtimeseat',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaa.showtime'),
        ),
    ]
