# Generated by Django 5.0 on 2024-01-08 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaa', '0013_alter_showtimeseat_showtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtimeseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaa.seat'),
        ),
    ]
