# Generated by Django 5.0 on 2024-01-09 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaa', '0014_alter_showtimeseat_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemaa.hall'),
        ),
    ]
