# Generated by Django 5.0 on 2023-12-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('trailer', models.FileField(blank=True, null=True, upload_to='video/')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=3, max_digits=5000, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('now', 'now'), ('soon', 'soon')], max_length=10)),
                ('released_date', models.DateField()),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('actor', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('genre', models.ManyToManyField(to='movie.genres')),
            ],
        ),
    ]
