# Generated by Django 5.0 on 2023-12-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_customerrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerrating',
            old_name='star',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='customerrating',
            old_name='customer',
            new_name='user',
        ),
    ]
