# Generated by Django 5.0 on 2023-12-21 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_schedulestaff'),
        ('movie', '0003_rename_star_customerrating_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user'),
        ),
    ]
